spring:
  application:
    name: openapi-app
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./testdb
    username: sa
    password: password
    sql-script-encoding: UTF-8